name: TourGuide Async CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    DOTNET_VERSION: '8.0.x'
    SOLUTION_FILE: 'TourGuide.sln'

jobs:
    build-and-test:
        name: Build & Test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
              os: [ ubuntu-latest, windows-latest ]
            fail-fast: false

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore Dependencies
              run: dotnet restore ${{ env.SOLUTION_FILE }}
              timeout-minutes: 5

            - name: Build Solution
              run: dotnet build ${{ env.SOLUTION_FILE }}
              timeout-minutes: 10

            - name: Run Tests
              run: dotnet test "${{ env.SOLUTION_FILE }}" --configuration Release --verbosity detailed --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"

              timeout-minutes: 20

            - name: Generate Coverage Report
              run: |
                dotnet tool install -g dotnet-reportgenerator-globaltool
                reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:Html
              if: success()

            - name: Upload Test Results & Coverage
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: test-results-${{ matrix.os }}
                path: |
                   **/test-results.trx
                   coveragereport/
                retention-days: 7

            - name: Publish Application
              run: |
                dotnet publish Api/TourGuide.csproj -c Release -o ./publish
                zip -r tourguide-async-${{ github.sha }}.zip ./publish
              if: github.event_name == 'push' && github.ref == 'refs/heads/master'

            - name: Upload Publish Artifact
              uses: actions/upload-artifact@v4
              if: github.event_name == 'push' && github.ref == 'refs/heads/master'
              with:
                name: tourguide-async-${{ github.sha }}
                path: tourguide-async-${{ github.sha }}.zip
                retention-days: 7